services:
  backend:
    container_name: backend-kalibr

    user: $USER

    working_dir: /scripts

    env_file:
      - path: /home/$USER/third_party/kalibr/.env

    volumes:
      - type: bind
        source: /home/$USER/third_party/kalibr/scripts
        target: /scripts

      - type: bind
        source: /home/$USER/Data
        target: /recordings