FROM osrf/ros:noetic-desktop-full

# Dependencies we use, catkin tools is very good build system
# https://github.com/ethz-asl/kalibr/wiki/installation
RUN export DEBIAN_FRONTEND=noninteractive \
	&& apt-get update && apt-get install -y \
	autoconf \
	automake \
	doxygen \
	git \
	ipython3 \
	libboost-all-dev \
	libblas-dev \
	libeigen3-dev \
	liblapack-dev \
	libopencv-dev \
	libpoco-dev \
	libsuitesparse-dev \
	libtbb-dev \
	libv4l-dev \
	locales \
	nano \
	python3-catkin-tools \
	python3-dev \
	python3-igraph \
	python3-matplotlib \
	python3-osrf-pycommon \
	python3-pip \
	python3-pyx \
	python3-scipy \
	python3-tk \
	python3-wxgtk4.0 \
	wget \
	&& rm -rf /var/lib/apt/lists/*

RUN locale-gen en_US en_US.UTF-8 \
	&& update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8

ENV LANG=en_US.UTF-8

ARG USERNAME=pointlaz
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN groupadd --gid $USER_GID $USERNAME \
	&& useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME \
	&& mkdir /home/$USERNAME/.config \
	&& chown $USER_UID:$USER_GID /home/$USERNAME/.config

RUN apt-get update \
	&& apt-get install -y sudo \
	&& echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/$USERNAME \
	&& chmod 0440 /etc/sudoers.d/$USERNAME \
	&& usermod -aG sudo $USERNAME \
	&& rm -rf /var/lib/apt/lists/*

USER $USERNAME

RUN rosdep update --rosdistro $ROS_DISTRO

# Create the workspace and build kalibr in it
ENV WORKSPACE=/home/$USERNAME/catkin_ws

RUN mkdir -p $WORKSPACE/src/kalibr \
	&& cd $WORKSPACE \
	&& catkin init \
	&& catkin config --extend /opt/ros/noetic \
	&& catkin config --cmake-args -DCMAKE_BUILD_TYPE=Release

WORKDIR ${WORKSPACE}/src/kalibr

COPY aslam_cv ./aslam_cv
COPY aslam_incremental_calibration ./aslam_incremental_calibration
COPY aslam_nonparametric_estimation ./aslam_nonparametric_estimation
COPY aslam_offline_calibration ./aslam_offline_calibration
COPY aslam_optimizer ./aslam_optimizer
COPY catkin_simple ./catkin_simple
COPY opencv2_catkin ./opencv2_catkin
COPY Schweizer-Messer ./Schweizer-Messer

WORKDIR ${WORKSPACE}

RUN catkin build -j$(nproc)

COPY entrypoint.sh /

WORKDIR /home/${USERNAME}

RUN echo "if [[ -e /opt/ros/${ROS_DISTRO}/setup.bash ]]; then source /opt/ros/${ROS_DISTRO}/setup.bash; fi" >> ~/.bashrc \
&& echo "if [[ -e ${WORKSPACE}/devel/setup.bash ]]; then source ${WORKSPACE}/devel/setup.bash; fi" >> ~/.bashrc

# When a user runs a command we will run this code before theirs
# This will allow for using the manual focal length if it fails to init
# https://github.com/ethz-asl/kalibr/pull/346
ENV KALIBR_MANUAL_FOCAL_LENGTH_INIT=1

ENTRYPOINT [ "/bin/bash", "/entrypoint.sh" ]
